-- Auto-generated: exercise GIF URLs from ExerciseDB OSS (https://oss.exercisedb.dev)
alter table exercises add column if not exists gif_url text;

update exercises set gif_url = 'https://static.exercisedb.dev/media/EIeI8Vf.gif' where name = 'Bench Press' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/3TZduzM.gif' where name = 'Incline Bench Press' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/GrO65fd.gif' where name = 'Decline Bench Press' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/SpYC0Kp.gif' where name = 'Dumbbell Chest Press' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/ns0SIbU.gif' where name = 'Incline Dumbbell Press' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/1PLE8e9.gif' where name = 'Chest Fly' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/0CXGHya.gif' where name = 'Cable Chest Fly' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/I4hDWkc.gif' where name = 'Push-Up' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/CB8WET1.gif' where name = 'Incline Push-Up' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/05Cf2v8.gif' where name = 'Dips' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/ila4NZS.gif' where name = 'Deadlift' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/o6LqKKP.gif' where name = 'Romanian Deadlift' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/r0z6xzQ.gif' where name = 'Barbell Row' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/BJ0Hz5L.gif' where name = 'Dumbbell Row' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/HMzLjXx.gif' where name = 'Pull-Up' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/dVeWXf2.gif' where name = 'Chin-Up' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/0MlxeMn.gif' where name = 'Lat Pulldown' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/A3P4O0R.gif' where name = 'Seated Cable Row' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/aaXr7ld.gif' where name = 'T-Bar Row' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/1xHyxys.gif' where name = 'Face Pull' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/1bQkKZK.gif' where name = 'Good Morning' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/Krmb3cB.gif' where name = 'Back Extension' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/kTbSH9h.gif' where name = 'Overhead Press' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/znQUdHY.gif' where name = 'Seated Dumbbell Press' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/eOrFCnx.gif' where name = 'Arnold Press' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/DsgkuIt.gif' where name = 'Lateral Raise' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/3eGE2JC.gif' where name = 'Front Raise' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/8DiFDVA.gif' where name = 'Rear Delt Fly' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/goJ6ezq.gif' where name = 'Cable Lateral Raise' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/UDlhcO8.gif' where name = 'Upright Row' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/cbuFJrn.gif' where name = 'Shrugs' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/25GPyDY.gif' where name = 'Barbell Curl' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/1VpF8db.gif' where name = 'Dumbbell Curl' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/2NpxjC1.gif' where name = 'Hammer Curl' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/ByX0WxV.gif' where name = 'Incline Dumbbell Curl' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/7D5bgLT.gif' where name = 'Preacher Curl' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/0IgNjSM.gif' where name = 'Concentration Curl' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/25GPyDY.gif' where name = 'EZ Bar Curl' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/gAwDzB3.gif' where name = 'Tricep Pushdown' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/1xHyxys.gif' where name = 'Overhead Tricep Extension' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/h8LFzo9.gif' where name = 'Skull Crusher' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/gx7s7uF.gif' where name = 'Close-Grip Bench Press' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/05Cf2v8.gif' where name = 'Tricep Dips' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/W6PxUkg.gif' where name = 'Kickbacks' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/soIB2rj.gif' where name = 'Diamond Push-Up' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/2dImyQ8.gif' where name = 'Wrist Curl' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/4Jc36XM.gif' where name = 'Reverse Wrist Curl' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/qPEzJjA.gif' where name = 'Farmers Walk' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/hCjGsRQ.gif' where name = 'Plank' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/9Ap7miY.gif' where name = 'Crunches' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/tZkGYZ9.gif' where name = 'Bicycle Crunch' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/0jp9Rlz.gif' where name = 'Leg Raise' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/fZFZ704.gif' where name = 'Russian Twist' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/xnInPfE.gif' where name = 'Ab Wheel Rollout' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/7xI5MXA.gif' where name = 'Cable Crunch' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/I3tsCnC.gif' where name = 'Hanging Leg Raise' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/5VXmnV5.gif' where name = 'Side Plank' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/qg2PGl6.gif' where name = 'Hip Thrust' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/GibBPPg.gif' where name = 'Glute Bridge' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/A2upspL.gif' where name = 'Donkey Kick' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/DhMl549.gif' where name = 'Squat' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/lFhb2Rw.gif' where name = 'Front Squat' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/yn8yg1r.gif' where name = 'Goblet Squat' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/5VCj6iH.gif' where name = 'Hack Squat' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/10Z2DXU.gif' where name = 'Leg Press' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/my33uHU.gif' where name = 'Leg Extension' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/HUEqZ1y.gif' where name = 'Bulgarian Split Squat' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/1VpF8db.gif' where name = 'Lunge' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/IZVHb27.gif' where name = 'Walking Lunge' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/76vfTdU.gif' where name = 'Step-Up' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/17lJ1kr.gif' where name = 'Leg Curl' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/Zg3XY7P.gif' where name = 'Seated Leg Curl' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/0rHfvy9.gif' where name = 'Nordic Curl' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/2Ty4idJ.gif' where name = 'Stiff-Leg Deadlift' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/0jp9Rlz.gif' where name = 'Standing Calf Raise' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/0S75mYG.gif' where name = 'Seated Calf Raise' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/A2upspL.gif' where name = 'Donkey Calf Raise' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/e1e76I2.gif' where name = 'Jump Rope' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/9c6T1YX.gif' where name = 'Stair Climber' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/PCUYOMs.gif' where name = 'Elliptical' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/SiWCcTN.gif' where name = 'Power Clean' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/SGY8Zui.gif' where name = 'Clean and Jerk' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/0dCyly0.gif' where name = 'Snatch' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/f7Y9eDZ.gif' where name = 'Thruster' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/dK9394r.gif' where name = 'Burpee' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/iPm26QU.gif' where name = 'Box Jump' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/UHJlbu3.gif' where name = 'Kettlebell Swing' and is_custom = false;
update exercises set gif_url = 'https://static.exercisedb.dev/media/Ha7SZ3y.gif' where name = 'Turkish Get-Up' and is_custom = false;
